spring:
  devtools:
    livereload:      enabled: true
  thymeleaf:    cache: false
  h2:
    console: #브라우저에서 바로 console로 접근 가능
      enabled: true
      path: /test_db #브라우저에서 들어갈 링크
      settings:
        web-allow-others: true
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:file:./h2/test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE #저장 할 경로 설정
    username: test
    password: 1234

logging:
  file:
    path: C:/var/log
  pattern:
    console: "[%-5level] %d{yyyy-MM-dd HH:mm:ss} : %30logger{5} - %msg%n"
    file: "[%-5level] %d{yyyy-MM-dd HH:mm:ss} : %30logger{5} - %msg%n"
  level:
    root: info
    com.hipporing.board: debug
    
#depth는 무조건 space 두번